server:
  port: 1763
spring:
   application:
     name: order-data-api
   datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/thoghti_order_db
     username: root
     password: 131612
   jpa:
     database-platform: org.hibernate.dialect.MySQL5Dialect 
     generate-ddl: true
     hibernate: 
         ddl-auto: update
         generate_statastics: true

logging:
  level:
    org:
     springframework:
       web: DEBUG
    root: WARN
